### ISSUE TITLE
Crash on iOS 9

### ISSUE THREAD

**Issue by isoiphone** [nicklockwood/GZIP#14]
gzippedDataWithCompressionLevel(0.1) is crashing 100% of the time.
OS Version:          iOS 9.0 (13A4305g)
Report Version:      105

I'm assuming it has to do with the line:
    void *libz = dlopen("libz.dylib", RTLD_NOW);

Unfortunately I can't get that specific. No interesting crash log to report. The symbolicated crash log for the line looks like this:
0   ???                                 000000000000000000 0 + 0

**Comment by nicklockwood** [comment]
I couldn't reproduce this on beta 4, but can you see if version 1.1.1 fixes it for you?
