### ISSUE TITLE
Add Carthage Support

### ISSUE THREAD

**Issue by dasmer** [nicklockwood/GZIP#16]
We're using GZIP and would love to be able to include it in our project via Carthage

**Comment by hyperspacemark** [comment]
Now that #17 is merged, it would be great if we could get a new tag that we can pin to. Bonus points for a pre-built binary!

**Comment by dasmer** [comment]
+1 @nicklockwood to do this, just create a binary:
```
carthage build --no-skip-current
carthage archive GZIP
```
and then create a release and attach it to that release.

If given push access, I would be happy to do it as well. Creating this binary would certainly speed up our development times!

**Comment by isoiphone** [comment]
+1

**Comment by a2** [comment]
Seems like [version 1.2](https://github.com/nicklockwood/GZIP/releases/tag/1.2) adds Carthage support.

**Comment by nicklockwood** [comment]
@a2 yes, but no pre-built binary.
