### ISSUE TITLE
Don't use dlopen and dlsym in iOS App Store project

### ISSUE THREAD

**Issue by sugarmo** [nicklockwood/GZIP#24]
We had been rejected because of this.

> This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

**Comment by nicklockwood** [comment]
Damn.

I'm only using it so you don't have to manually import libz in your project, so it should be possible to do without it. It's annoying though.

**Comment by yaakov-h** [comment]
> This includes any code which passes **arbitrary** parameters to dynamic methods such as dlopen(), dlsym()...

Maybe I'm missing something but this code appears to only pass hardcoded parameters, not arbitrary/dynamic ones. 😕

**Comment by nicklockwood** [comment]
@yaakov-h you're right, and it might get through on appeal, but it's probably easier if I just remove it.

**Comment by nicklockwood** [comment]
@sugarmo OK I've released version 1.2 that doesn't use dlopen.

**Comment by sugarmo** [comment]
@nicklockwood Thank you so much.
