### ISSUE TITLE
Missing PrivacyInfo file

### ISSUE THREAD

**Issue by ju135** [nicklockwood/GZIP#50]
The PrivacyInfo file is missing even though the File timestamp API is used.

I found usages of the following file timestamp APIs:

- `.modificationDate`
- `.fileModificationDate`
- `lstat`

See [Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393)

**Comment by nicklockwood** [comment]
@ju135 I don't see any reference to these APIs in the code. Can you point out where you think they are being used?

**Comment by ju135** [comment]
You are right, sorry I mixed something up - they were used by another pod that uses a different library for handling zip files.
I'll close this issue - thank you for looking into it!
