### ISSUE TITLE
About Z_BEST_COMPRESSION

### ISSUE THREAD

**Issue by shidongdong** [nicklockwood/GZIP#8]
hi,I use your open source for gzip,but i want to use best compression,so i change parms use best compression,but data isn't less than use default compression,
as:
#define Z_NO_COMPRESSION         0
#define Z_BEST_SPEED             1
#define Z_BEST_COMPRESSION       9
#define Z_DEFAULT_COMPRESSION  (-1)

**Comment by nicklockwood** [comment]
There's no  guarantee that Z_BEST_COMPRESSION will make the file smaller, just that it won't make it bigger.
